project:
  type: website

website:
  title: "Treasury Coin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Details
        menu:
          - href: seigniorage.qmd
          - href: technical.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



