---
title: "Treasury Coin"
---

The United States Government should create a "Treasury Coin" --- call it "T-coin" for short --- based on the protocol behind Bitcoin. T-coin would be the first government-supported anonymous, decentralized currency. Key points:


* Bitcoin has a market capitalization --- meaning coin price in dollars multiplied by total number of coins --- of around $2 trillion. This is a large enough number that something new, like T-coin, might have a meaningful impact on the US debt.

* All the code for the Bitcoin blockchain is, by design, open source. There are no secrets. Nothing prevents us from copying Bitcoin down to the very last detail. We would call it the "T-chain".

* The Government could support the project by allowing people and business to pay their taxes with T-coin. Allowing, or even requiring, the use of a new currency for paying taxes is a tried and true method for governments throughout history to incentivise its use.

* There are two methods by which the US Government might benefit from T-coin directly. First, before releasing the project to the public, we could "[premine](https://www.investopedia.com/terms/p/premining.asp)" a third or so of the total number of coins. Second, we could make a simple change in the protocol by which the US Government would receive a fraction of the coin reward each time a new block is created. From a political economy point of view, it might make more sense to do a smaller premine while taking a larger share of newly created coins, if only to avoid giving the Federal Government too large of an initial windfall.

* Our Treasury Coin plan is completely different from the usual [Central Bank Digital Currency](https://en.wikipedia.org/wiki/Central_bank_digital_currency) (CBDC) projects because it uses the privacy-protecting Bitcoin protocol. The central benefit is we inherit all the positive properties of Bitcoin which lend it tremendous appeal and market cap. The central cost of using a system like Bitcoin is that, like physical cash, it allows for anonymous use. Criminals would be able to use T-coins, just as they currently use bitcoins and cash, to hide their activities from the government. Allowing this use seems a small price to pay in order to reap the financial rewards associated with creating Treasury Coins.

* We still use dollars. Federal workers are paid in dollars. Social security checks are denominated in dollars. The value of T-coins will float relative to dollars. The USG could bring some stability to the value of T-coins by having a regular off-chain auction, similar to the auctions which the US Treasury currently holds for new debt issuance. A daily (or weekly or monthly) auction for T-coins could set the "official" exchange rate for T-coins to dollars until the next auction, thereby decreasing, at least somewhat, its volatility for everyday use.

* T-coins are likely to be much more useful than bitcoins because the US Government would have every incentive to ensure that they are. Every action which makes T-coins more valuable causes a significant increase in the dollar value of the T-coins which the USG already owns (after premining) and which it will continue to receive as new coins are mined. The USG could encourage and/or require various entities to accept T-coins for payment.

* T-coins are likely to be the most secure blockchain currency in the world because the US Government would have every incentive to make it secure.

How much might T-coin help the US? Note that Dogecoin, a digital currency based on the Bitcoin protocol but created initially as a joke, has a market cap of around \$64 billion. If Bitcoin is worth 33 times more than Dogecoin, despite being a fundamentally similar creation, why couldn't T-coin be worth 50 times more than Bitcoin? At that valuation, just the premined portion of T-coin would allow the US Government to pay-off its \$33 trillion debt. The coins which came to the Government as the system continued to run in the years which followed would contribute significantly to future spending.

How is this possible? How could the US Government create, out of nothing, a digital currency which would allow it to pay off a \$33 trillion debt? The magic happens when we capture the [seigniorage](https://en.wikipedia.org/wiki/Seigniorage) benefit of creating the first government-supported anonymous, decentralized currency.

If you want further updates, [sign up for our Substack](https://treasurycoin.substack.com/).

